name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'Reegan'

jobs:
  Job1:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Greetings from ${{ inputs.name }}"
  Job2:
    runs-on: ubuntu-latest

    steps:
      - name: Welcome
        run: echo "Welcome from ${{ inputs.name }}"
  

