name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'Reegan'

jobs:
  Environment-Setup:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Greetings from ${{ inputs.name }}"
  Building-Application:
    runs-on: ubuntu-latest
    needs: Environment-Setup
    steps:
      - name: Welcome
        run: echo "Welcome from ${{ inputs.name }}"
  

